name: C++ Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y cmake g++ googletest

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build
